function add(a, b){
    return a + b;
}

function substraction(a, b){
    return a - b;
}

function multiplication (a, b){
    return a * b;
}

function division (a, b){
    return a / b;
}

let sum = add(10, 5);
let difference = substraction(10, 5);
let product = multiplication(10, 5);
let quotient = division(10, 5);

console.log(`The sum is: ${sum}`);
console.log(`The difference is: ${difference}`);
console.log(`The product is: ${difference}`);
console.log(`The quotient is: ${quotient}`);   